src/main/java/com/g3bookstore/entities/Book.java
package com.g3bookstore.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Lob;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Entity class for Books.
 * 
 * @author Alessandro, Denis, Kevin, Werner
 */
@Entity
@Table(name = "book", catalog = "BOOKSTORE", schema = "")
@NamedQueries({
    @NamedQuery(name = "Book.findAll", query = "SELECT b FROM Book b")
    , @NamedQuery(name = "Book.findByBookId", query = "SELECT b FROM Book b WHERE b.bookId = :bookId")
    , @NamedQuery(name = "Book.findByIsbn", query = "SELECT b FROM Book b WHERE b.isbn = :isbn")
    , @NamedQuery(name = "Book.findByTitle", query = "SELECT b FROM Book b WHERE b.title = :title")
    , @NamedQuery(name = "Book.findByPubDate", query = "SELECT b FROM Book b WHERE b.pubDate = :pubDate")
    , @NamedQuery(name = "Book.findByInventoryDate", query = "SELECT b FROM Book b WHERE b.inventoryDate = :inventoryDate")
    , @NamedQuery(name = "Book.findByPage", query = "SELECT b FROM Book b WHERE b.page = :page")
    , @NamedQuery(name = "Book.findByListPrice", query = "SELECT b FROM Book b WHERE b.listPrice = :listPrice")
    , @NamedQuery(name = "Book.findBySalePrice", query = "SELECT b FROM Book b WHERE b.salePrice = :salePrice")
    , @NamedQuery(name = "Book.findByWholesalePrice", query = "SELECT b FROM Book b WHERE b.wholesalePrice = :wholesalePrice")
    , @NamedQuery(name = "Book.findByRemoved", query = "SELECT b FROM Book b WHERE b.removed = :removed")
    , @NamedQuery(name = "Book.findByTotalSale", query = "SELECT b FROM Book b WHERE b.totalSale = :totalSale")
    , @NamedQuery(name = "Book.findByImage", query = "SELECT b FROM Book b WHERE b.image = :image")})
public class Book implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "book_id")
    private Integer bookId;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 10)
    @Column(name = "isbn")
    private String isbn;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 150)
    @Column(name = "Title")
    private String title;
    @Lob
    @Size(max = 16777215)
    @Column(name = "description")
    private String description;
    @Basic(optional = false)
    @NotNull
    @Column(name = "pub_date")
    @Temporal(TemporalType.DATE)
    private Date pubDate;
    @Basic(optional = false)
    @NotNull
    @Column(name = "inventory_date")
    @Temporal(TemporalType.DATE)
    private Date inventoryDate;
    @Basic(optional = false)
    @NotNull
    @Column(name = "page")
    private int page;
    // @Max(value=?)  @Min(value=?)//if you know range of your decimal fields consider using these annotations to enforce field validation
    @Column(name = "list_price")
    private BigDecimal listPrice;
    @Column(name = "sale_price")
    private BigDecimal salePrice;
    @Column(name = "wholesale_price")
    private BigDecimal wholesalePrice;
    @Basic(optional = false)
    @NotNull
    @Column(name = "removed")
    private boolean removed;
    @Basic(optional = false)
    @NotNull
    @Column(name = "total_sale")
    private int totalSale;
    @Size(max = 100)
    @Column(name = "image")
    private String image;
    @JoinTable(name = "book_author", joinColumns = {
        @JoinColumn(name = "book_id", referencedColumnName = "book_id")}, inverseJoinColumns = {
        @JoinColumn(name = "author_id", referencedColumnName = "author_id")})
    @ManyToMany
    private List<Author> authorList;
    @JoinTable(name = "book_genre", joinColumns = {
        @JoinColumn(name = "book_id", referencedColumnName = "book_id")}, inverseJoinColumns = {
        @JoinColumn(name = "genre_id", referencedColumnName = "genre_id")})
    @ManyToMany
    private List<Genre> genreList;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "bookId")
    private List<DetailInvoice> detailInvoiceList;
    @JoinColumn(name = "publisher_id", referencedColumnName = "publisher_id")
    @ManyToOne(optional = false)
    private Publisher publisherId;
    @JoinColumn(name = "format_id", referencedColumnName = "format_id")
    @ManyToOne(optional = false)
    private EbookFormat formatId;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "bookId")
    private List<Review> reviewList;

    public Book() {
    }

    public Book(Integer bookId) {
        this.bookId = bookId;
    }

    public Book(Integer bookId, String isbn, String title, Date pubDate, Date inventoryDate, int page, boolean removed, int totalSale) {
        this.bookId = bookId;
        this.isbn = isbn;
        this.title = title;
        this.pubDate = pubDate;
        this.inventoryDate = inventoryDate;
        this.page = page;
        this.removed = removed;
        this.totalSale = totalSale;
    }

    public Integer getBookId() {
        return bookId;
    }

    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    public String getIsbn() {
        return isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Date getPubDate() {
        return pubDate;
    }

    public void setPubDate(Date pubDate) {
        this.pubDate = pubDate;
    }

    public Date getInventoryDate() {
        return inventoryDate;
    }

    public void setInventoryDate(Date inventoryDate) {
        this.inventoryDate = inventoryDate;
    }

    public int getPage() {
        return page;
    }

    public void setPage(int page) {
        this.page = page;
    }

    public BigDecimal getListPrice() {
        return listPrice;
    }

    public void setListPrice(BigDecimal listPrice) {
        this.listPrice = listPrice;
    }

    public BigDecimal getSalePrice() {
        return salePrice;
    }

    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    public BigDecimal getWholesalePrice() {
        return wholesalePrice;
    }

    public void setWholesalePrice(BigDecimal wholesalePrice) {
        this.wholesalePrice = wholesalePrice;
    }

    public boolean getRemoved() {
        return removed;
    }

    public void setRemoved(boolean removed) {
        this.removed = removed;
    }

    public int getTotalSale() {
        return totalSale;
    }

    public void setTotalSale(int totalSale) {
        this.totalSale = totalSale;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public List<Author> getAuthorList() {
        return authorList;
    }

    public void setAuthorList(List<Author> authorList) {
        this.authorList = authorList;
    }

    public List<Genre> getGenreList() {
        return genreList;
    }

    public void setGenreList(List<Genre> genreList) {
        this.genreList = genreList;
    }

    public List<DetailInvoice> getDetailInvoiceList() {
        return detailInvoiceList;
    }

    public void setDetailInvoiceList(List<DetailInvoice> detailInvoiceList) {
        this.detailInvoiceList = detailInvoiceList;
    }

    public Publisher getPublisherId() {
        return publisherId;
    }

    public void setPublisherId(Publisher publisherId) {
        this.publisherId = publisherId;
    }

    public EbookFormat getFormatId() {
        return formatId;
    }

    public void setFormatId(EbookFormat formatId) {
        this.formatId = formatId;
    }

    public List<Review> getReviewList() {
        return reviewList;
    }

    public void setReviewList(List<Review> reviewList) {
        this.reviewList = reviewList;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (bookId != null ? bookId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Book)) {
            return false;
        }
        Book other = (Book) object;
        if ((this.bookId == null && other.bookId != null) || (this.bookId != null && !this.bookId.equals(other.bookId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.g3bookstore.entities.Book[ bookId=" + bookId + " ]";
    }
    
}

src/main/java/com/g3bookstore/backingbeans/BookBackingBean.java
package com.g3bookstore.backingbeans;

import com.g3bookstore.customcontrollers.CustomBookJpaController;
import com.g3bookstore.customcontrollers.CustomClientJpaController;
import com.g3bookstore.entities.Book;
import com.g3bookstore.entities.Client;
import com.g3bookstore.entities.Genre;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.enterprise.context.SessionScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

/**
 * This class will take care of all the back end operations for the book page
 *
 * @author Kevin Bui
 */
@Named("BookBean")
@ManagedBean
@SessionScoped
public class BookBackingBean implements Serializable {

    @Inject
    private CustomClientJpaController clientController;

    @Inject
    private CustomBookJpaController bookController;

    @Inject
    private ClientCookieTracker cct;

    private static final Logger log = Logger.getLogger(BookBackingBean.class.getName());
    private Book book;

    /**
     * Returns the book object
     *
     * @return
     */
    public Book getBook() {
        return book;
    }

    /**
     * Sets the book object
     *
     * @param book
     */
    public void setBook(Book book) {
        this.book = book;
    }

    /**
     * Initializes sets the cookie
     */
    public void init() {
        if (getBooksInfo() == null) {
            FacesContext facesContext = FacesContext.getCurrentInstance();
            String outcome = "/WEB-INF/errors/404.xhtml";
            facesContext.getApplication().getNavigationHandler().handleNavigation(facesContext, null, outcome);
        } else {
            book = getBooksInfo();
            cct.saveGenreToDBAndCookie(book.getGenreList().get(0));
        }
    }

    /**
     * Returns a book object with all its information
     *
     * @return The book object
     */
    public Book getBooksInfo() {
        Map<String, String> parameters = FacesContext.getCurrentInstance().
                getExternalContext().getRequestParameterMap();

        log.log(Level.INFO, null, parameters.get("bookid"));

        // Check the query string
        try {
            String bookId = parameters.get("bookid");
            if (bookId == null || !bookId.matches("^[0-9]+]*$")) {
                return null;
            }

            int bookIdParsed = Integer.parseInt(bookId);
            if (validateBookId(bookIdParsed) == false) {
                return null;
            }

            return bookController.getBookByID(bookIdParsed);
        } catch (IllegalArgumentException ex) {
            log.log(Level.INFO, null, ex);
        }
        return null;
    }

    /**
     * Returns true if the book is on sale
     *
     * @return
     */
    public boolean checkBookOnSale() {
        Book b = getBooksInfo();

        if (b == null || b.getSalePrice() == null) {
            return false;
        }
        if (b.getSalePrice().intValue() > 0) {
            return true;
        }

        return false;
    }

    /**
     * Returns the similar books by genre.
     *
     * @return THe list of similar books
     */
    public List<Book> getSimilarBooksByGenre() {
        return bookController.getSimilarGenreBooks(bookController.getBookByID(book.getBookId()));
    }

    /**
     * Returns the similar books by author.
     *
     * @return THe list of similar books
     */
    public List<Book> getSimilarBooksByAuthor() {
        return bookController.getSimilarAuthorBooks(bookController.getBookByID(book.getBookId()));
    }

    /**
     * Checks if the list of authors is empty or not.
     *
     * @param b
     * @return
     */
    public boolean checkIfSimilarAuthorIsZero(Book b) {
        if (getSimilarBooksByAuthor() == null) {
            return false;
        }

        return (getSimilarBooksByAuthor().size() == 0) ? true : false;
    }

    /**
     * Returns a list of the most recent books added to the book store
     *
     * @return The list of books recently added to the bookstore
     */
    public List<Book> getMostRecentBooks(int size) {
        return (List<Book>) bookController.getMostRecentBooks(size);

    }

    /**
     * Returns all the books that are on sale.
     *
     * @return The list of books on sale
     */
    public List<Book> getBooksOnSale() {
        return (List<Book>) bookController.getBooksOnSale();
    }

    /**
     * Returns a specific amount of books on sale
     *
     * @param size The amount wanted
     * @return The list of books on sale
     */
    public List<Book> getBooksOnSale(int size) {
        return (List<Book>) bookController.getBooksOnSale(size);
    }

    /**
     * Returns a list of recommended books
     *
     * @param size
     * @return
     */
    public List<Book> getRecommendedBooks(int size, String email) {
        List<Client> c = clientController.getClientByEmail(email);
        List<Book> empty = new ArrayList<Book>();
        if (c.size() > 0) {
            cct.setClient(c.get(0));
            Genre g = cct.getLastGenreVisitedByClient();
            if (g != null) {
                return shuffleList(bookController.getBooksByGenre(g), size);
            }
        } 
        
        return empty;

    }

    /**
     * Returns a list of recommended books
     *
     * @param size
     * @return
     */
    public List<Book> getRecommendedBooksNotLogged(int size) {
        Genre g = cct.getLastGenreVisitedByClient();
        return shuffleList(bookController.getBooksByGenre(g), size);
    }

    /**
     * Shuffles a list of book with no duplicates and a specific size
     *
     * @param list The list of books
     * @return A list of recommended books with a specific size
     */
    private List<Book> shuffleList(List<Book> list, int size) {
        Collections.shuffle(list);

        Set<Book> bookSet = new HashSet<Book>();
        List<Book> noDuplicates = new ArrayList<Book>();
        List<Book> newList = new ArrayList<Book>();
        for (Book b : list) {
            noDuplicates.add(b);
        }

        bookSet.addAll(noDuplicates);
        noDuplicates.clear();
        noDuplicates.addAll(bookSet);

        if (noDuplicates.size() < size) {
            return noDuplicates;
        } else {
            for (int i = 0; i < size; i++) {
                newList.add(noDuplicates.get(i));
            }
        }

        return newList;
    }

    /**
     * Returns true if the id is a valid one.
     *
     * @param id The id of the book to be checked
     * @return true if the id is valid, else false
     */
    private boolean validateBookId(int id) {
        int size = bookController.getBooks().size();
        boolean valid = true;

        if (id < 1 || id > size) {
            valid = false;
        }

        return valid;
    }
}

src/main/webapp/client/advanced_search.xhtml
<!-- @author: Kevin, Alessandro -->

<ui:composition
    template="/WEB-INF/templates/masterTemplate.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="placeholder-css">
        <h:outputStylesheet library="css" name="advancedsearch.css" />
    </ui:define>

    <ui:define name="windowTitle">
        #{msgs.search}
    </ui:define>

    <ui:define name="content">
        <f:metadata>
            <f:event type="preRenderView" listener='#{loginBean.setPreviousPage("/client/advanced_search.xhtml")}' />
            <f:event type="preRenderView" listener='#{cartBean.setAlreadyInCart(false)}' />
        </f:metadata>
        <div class="container card margin-top-xl">
            <div class="row padding-m">
                <h1 class="text-center a-header text-uppercase as-header">#{msgs.advancedsearch}</h1>
                <h:form id="searchForm" class="form-horizontal">   
                    <!-- Dropdown selection for the search -->
                    <div class="form-group" id="searchgrid">
                        <h:outputLabel for="choice" value="#{msgs.user_choice}" class="control-label col-sm-4"/>     
                        <div class="col-sm-4">
                            <h:selectOneMenu id="choice" value="#{searchBackingBean.choice}" required="true" class="form-control custom-select">
                                <f:selectItem itemLabel="#{msgs.search_author}" itemValue="Author" />
                                <f:selectItem itemLabel="#{msgs.search_publisher}" itemValue="Publisher" />
                                <f:selectItem itemLabel="#{msgs.search_title}" itemValue="Title"/>
                                <f:selectItem itemLabel="#{msgs.search_isbn}" itemValue="ISBN"/>
                            </h:selectOneMenu>
                        </div>       
                        <h:message class="error" for="searchForm" id="searchFormMessage" />  
                    </div>
                    <!-- Textbox for specific keyword search -->
                    <div class="form-group">
                        <h:outputLabel  for="input" rendered="#{!searchBackingBean.choice}" value="#{msgs.keyword_search}" 
                                        class="control-label col-sm-4"/>
                        <div class="col-sm-4">
                            <h:inputText  id="input"  rendered="#{!searchBackingBean.choice}" requiredMessage="#{msgs.empty_field}"
                                          value="#{searchBackingBean.keyword}" required="true" class="form-control"/>
                        </div>
                    </div>

                    <!-- Button -->
                    <div class="text-center">
                        <h:commandButton id="search" action="#{searchBackingBean.search()}" value="#{msgs.search}" class="btn btn-outlined btn-primary signup-button"/>
                    </div>
                </h:form>
                <p:outputPanel styleClass="panel-group" id="accordion">
                    <a class="accordion-toggle text-center tips-link text-uppercase" data-toggle="collapse" data-parent="#accordion" href="#collapse">#{msgs.tips}</a>
                    <div id="collapse" class="panel-collapse collapse">
                        <span class="tips-text text-center">#{msgs.tip1}</span>
                        <span class="tips-text text-center">#{msgs.tip2}</span>
                        <span class="tips-text text-center">#{msgs.tip3}</span>
                        <span class="tips-text text-center">#{msgs.tip4}</span>
                        <span class="tips-text text-center">#{msgs.tip5}</span>
                        <span class="tips-text text-center">#{msgs.tip6}</span>
                        <span class="tips-text text-center">#{msgs.tip7}</span>
                    </div>
                </p:outputPanel>
            </div>
        </div>
    </ui:define> 
</ui:composition>

src/main/webapp/client/confirmed_cart.xhtml
<!-- Alessandro -->
<ui:composition
    template="/WEB-INF/templates/masterTemplate.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="placeholder-css">
        <h:outputStylesheet library="css" name="confirmed_cart.css" />
    </ui:define>

    <ui:define name="windowTitle">
        #{msgs.shoppingcart}
    </ui:define>

    <ui:define name="content">
        <f:metadata>
            <f:event type="preRenderView" listener='#{loginBean.setPreviousPage("/client/confirmed_cart.xhtml")}' />
            <f:event type="preRenderView" listener='#{checkoutBean.setBookList(cartBean.bookList)}' />

        </f:metadata>
        <ui:fragment rendered="#{cartBean.alreadyInCart}">
            <div class="container margin-top-xl cart-container ">
                <div class="row">
                    <div class="col-md-1 col-sm-1 col-xs-1">
                        <span class="menu-icon fa fa-times"></span>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-3">
                        <a href="book.xhtml?bookid=#{BookBean.book.bookId}">
                            <h:graphicImage class="book-image-list margin-top-book" style="width: 48px; height: 75px; opacity: 0.9;" name="images/smallcovers/#{BookBean.book.image}" />
                        </a> 
                    </div>
                    <div class="col-md-2 col-sm-2 col-xs-2 ">
                        <span class="confirmedAlreadyAdded-header">#{msgs.alreadyadded}</span>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-3 ">
                        <span class="confirmedAdded-subtotal">#{msgs.cartSubtotal} (#{cartBean.totalItems()} #{msgs.itemName}): </span>  
                        <span class="subtotal-price">$#{cartBean.getPriceNoTax()}</span>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-3 ">
                        <h:link id="cartBtnAlreadyInCart" outcome="/client/shopping_cart.xhtml">
                            <span class="btn btn-outlined btn-primary cart-btn">
                                #{msgs.cart}
                            </span>
                        </h:link>
                        <h:link onclick="#{checkoutBean.setBookList(cartBean.bookList)}" outcome="/client/checkout.xhtml">
                            <span class="btn btn-outlined btn-primary cart-btn">
                                #{msgs.proceedBtn} (#{cartBean.totalItems()} #{msgs.itemName})
                            </span>
                        </h:link>   
                    </div>
                </div>
            </div>
        </ui:fragment>
        <ui:fragment rendered="#{!cartBean.alreadyInCart}">
            <div class="container margin-top-xl cart-container ">
                <div class="row">
                    <div class="shipping-container container">
                        <div class="col-md-1 col-sm-1 col-xs-1 margin-middle">
                            <span class="menu-icon fa fa-check"></span>
                        </div>
                        <div class="col-md-3 col-sm-3 col-xs-3 ">
                            <a href="book.xhtml?bookid=#{BookBean.book.bookId}">
                                <h:graphicImage class="book-image-list margin-top-book" style="width: 48px; height: 75px; opacity: 0.9;" name="images/smallcovers/#{BookBean.book.image}" />
                            </a> 
                        </div>
                        <div class="col-md-2 col-sm-2 col-xs-2 margin-middle">
                            <span class="confirmedAdded-header">#{msgs.added}</span>
                        </div>
                        <div class="col-md-3 col-sm-3 col-xs-3 margin-middle" >
                            <span class="confirmedAdded-subtotal">#{msgs.cartSubtotal} (#{cartBean.totalItems()} #{msgs.itemName}): </span>  
                            <span class="subtotal-price">$#{cartBean.getPriceNoTax()}</span>
                        </div>
                        <div class="col-md-3 col-sm-3 col-xs-3 margin-middle">
                            <h:link id="cartBtn" outcome="/client/shopping_cart.xhtml">
                                <span class="btn btn-outlined btn-primary cart-btn">
                                    #{msgs.cart}
                                </span>
                            </h:link>
                            <h:link outcome="/client/checkout.xhtml">
                                <span class="btn btn-outlined btn-primary cart-btn">
                                    #{msgs.proceedBtn} (#{cartBean.totalItems()} #{msgs.itemName})
                                </span>
                            </h:link>   
                        </div>
                    </div>
                </div>
            </div>
        </ui:fragment>

        <div class="container book-container scroller">
            <div class="row padding-m ">
                <span class="confirmedAdded-genreHeader">#{msgs.booksonsale}</span>
                <hr/>    
                <ui:repeat value="#{BookBean.getBooksOnSale(4)}" var="book">
                    <div class="col-md-3 col-sm-6 col-xs-6 first-row">
                        <div class="book-row">
                            <div class="">
                                <a href="book.xhtml?bookid=#{book.bookId}">
                                    <div class="similar-genre-books">
                                        <h:graphicImage class="img img-responsive" style="width: auto; height: auto; opacity: 0.8;" name="images/smallcovers/#{book.image}" />
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </ui:repeat>
                <span class="confirmedAdded-genreHeader">#{msgs.booksrecentlyadded}</span>
                <hr/>    
                <ui:repeat value="#{BookBean.getMostRecentBooks(4)}" var="book">
                    <div class="col-md-3 col-sm-6 col-xs-6 first-row">
                        <div class="book-row">
                            <div class="">
                                <a href="book.xhtml?bookid=#{book.bookId}">
                                    <div class="similar-genre-books">
                                        <h:graphicImage class="book-image-list-genres" style="width: auto; height: auto; opacity: 0.8;" name="images/smallcovers/#{book.image}" />
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </ui:repeat>
                <span class="confirmedAdded-genreHeader">#{msgs.similarbooksbygenre}</span>
                <hr/>    
                <ui:repeat value="#{BookBean.similarBooksByGenre}" var="book">
                    <div class="col-md-3 col-sm-6 col-xs-6">
                        <div class="book-row">
                            <div class="">
                                <a href="book.xhtml?bookid=#{book.bookId}">
                                    <div class="similar-genre-books">
                                        <h:graphicImage class="img img-responsive" style="width: auto; height: auto; opacity: 0.8;" name="images/smallcovers/#{book.image}" />
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </ui:repeat>
                <ui:fragment rendered="#{!BookBean.checkIfSimilarAuthorIsZero(BookBean.book)}">
                    <span class="confirmedAdded-genreHeader">#{msgs.booksbysimilarauthor}</span>
                    <hr/>    
                    <ui:repeat value="#{BookBean.similarBooksByAuthor}" var="book">
                        <div class="col-md-3 col-sm-6 col-xs-6">
                            <div class="book-row">
                                <div class=" ">
                                    <a href="book.xhtml?bookid=#{book.bookId}">
                                        <div class="similar-genre-books">
                                            <h:graphicImage class="img img-responsive" style="width: auto; height: auto; opacity: 0.8;" name="images/smallcovers/#{book.image}" />
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </ui:repeat>
                </ui:fragment>
            </div>
        </div>
    </ui:define> 
</ui:composition>

src/main/webapp/client/email_success.xhtml
<!-- @author: Kevin -->

<ui:composition
    template="/WEB-INF/templates/masterTemplate.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="head-meta">
        <meta http-equiv="refresh" content="3;URL=#{request.contextPath}/client/orderdetails.xhtml" />
    </ui:define>

    <ui:define name="placeholder-css">
        <h:outputStylesheet library="css" name="success.css" />
    </ui:define>

    <ui:define name="windowTitle">
        #{msgs.success_email}
    </ui:define>

    <ui:define name="content">
        <f:metadata>
            <f:event type="preRenderView" listener="#{loginBean.checkLoggedIn()}" />
            <f:event type="preRenderView" listener='#{cartBean.setAlreadyInCart(false)}' />
        </f:metadata>
        <div class="margin-top-xl success-container">
            <div class="row padding-m">
                <h1 class="a-header success-header">#{msgs.success_email}</h1>
                <hr class="bar"/>
                <span class="redirect-text">#{msgs.email_message} #{MyOrdersBean.client.email}</span>
            </div>
        </div>
    </ui:define> 

</ui:composition>